updates to support export process to bpmn20 xml file with all form de…
relational-data-systems/flowable-engine pull request #31
Opened 2018-05-02 03:28 UTC by simon998yang

…finitions embeded (referenced form not resolved, so we can import all individual forms later on.  For deployment, we still export form with form reference form resolved)

2018-05-02 04:34 UTC, ruiboy commented on modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/app/service/api/ModelService.java
> +    BpmnModel getBpmnModel(AbstractModel model, Map<String, Model> formMap, Map<String, Model> decisionTableMap, boolean resolveFormReference);
Should we be making breaking changes to the API of this class?  Wont that make it harder to upgrade flowable versions?   Shouldn't we keep the existing method and just have it call our new impl with boolean=false?

2018-05-02 04:36 UTC, ruiboy commented on modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/app/service/editor/FlowableModelQueryService.java
> +    public Object importProcessModel(HttpServletRequest request, MultipartFile file, boolean overwrite) {
again, should be breaking the public API like this?

2018-05-02 04:39 UTC, ruiboy requested changes
A couple of comments within.

2018-05-03 03:16 UTC, simon998yang commented on modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/app/service/api/ModelService.java
> +    BpmnModel getBpmnModel(AbstractModel model, Map<String, Model> formMap, Map<String, Model> decisionTableMap, boolean resolveFormReference);
right. added it back

2018-05-03 03:16 UTC, simon998yang commented on modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/app/service/editor/FlowableModelQueryService.java
> +    public Object importProcessModel(HttpServletRequest request, MultipartFile file, boolean overwrite) {
underlying problem here is that flowable return html for ajax call exception (which we can enhance it to return json like we did for gasp) , but flowable wrapping all exception simply in BadReqeustException. and cannot carry structural data except the exception message. Here I need to return something like {'existingProcess': 'pKey', 'existingForms': ['fKey1', 'fKey2]} to show a confirmation window for overwriting. 

I checked again in system builder and gasp , there seems no neat way to use exception to carry other structural information back to client except the error message?

2018-05-03 03:29 UTC, ruiboy commented on modules/flowable-ui-modeler/flowable-ui-modeler-logic/src/main/java/org/flowable/app/service/editor/FlowableModelQueryService.java
> +    public Object importProcessModel(HttpServletRequest request, MultipartFile file, boolean overwrite) {
okay -- leave that as is.   might be useful to add your comment to source code though ??

2018-05-03 03:29 UTC, ruiboy approved these changes

2018-05-03 03:38 UTC, merged